typography_spectrum: 0.05454796110279858
color:
  brandStrength: 0.324193196836859
  lightness: 0.1288340596947819
  saturation: 0.8933026783633977
  rhythmicContrast: 0.14947996172122657
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
opengraph:
  type: ''
layout_spectrum: 0.21707745920866728
author:
  name: Peter Rutter
  email: peter@vfecustom.com
  url: vfepedals.com
name: VFE Pedals
title: Taking Pedals to School
description: 'Custom Pedals, Meet Eduation'
